Refactor Functions
ichiro-its/akushon pull request #23
Opened 2021-06-08 20:36 UTC by segara2410

Change some function flows and parameters.

2021-06-09 03:26 UTC, threeal requested changes
See the comment for the requested changes. Also, i think it's better to process action using each action class instead of managing all into one action manager class.

2021-06-09 03:26 UTC, threeal commented on src/akushon/action_manager.cpp
> +    if (action_name == action_names[id]) {
Use `std::find` instead, see https://en.cppreference.com/w/cpp/algorithm/find.

2021-06-10 04:09 UTC, threeal approved these changes
Still not perfect, but it's okay

2021-06-10 16:44 UTC, maroqijalil approved these changes
LGTm

2021-06-10 16:44 UTC, merged