Add function to get joints
ichiro-its/akushon pull request #25
Opened 2021-06-18 11:52 UTC by segara2410

Add function to get joints from robot pose.

2021-06-18 12:22 UTC, threeal requested changes
Use `T foo() const` for getter. And return a const reference if it's possible.

2021-06-19 12:17 UTC, threeal submitted a review, later dismissed
looks good to me.

2021-06-19 18:05 UTC, finesaaa approved these changes
Good

2021-06-19 18:07 UTC, Nathan24zz approved these changes
LGTM

2021-06-19 18:07 UTC, merged