[Enhancement] - Refactor Akushon
ichiro-its/akushon pull request #41
Opened 2024-04-14 14:44 UTC by FaaizHaikal

## Jira Link: 

## Description

- Fix error in loading config and add logging
- Fix pose index when playing next action
- Use argument for ```action_main.cpp``` for flexibility in checking actions
- Remove data config (moved to https://github.com/ichiro-its/configuration)

## Type of Change

- [x] Bugfix
- [x] Enhancement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [x] Manual tested.

## Checklist:

- [x] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2024-04-14 15:22 UTC, JayantiTA approved these changes

2024-04-19 08:20 UTC, threeal requested changes

2024-04-19 08:20 UTC, threeal commented on src/action_main.cpp
> +  std::string action_name = "";
The `action_name` is not being modified after declaration, i guess it should extract a value from the arguments.

2024-04-19 08:20 UTC, threeal commented on src/action_main.cpp
> +    std::cout << help_message;
I suggest using `std::cerr` in favor of `std::cout` for printing errors.

2024-04-19 08:20 UTC, threeal commented on src/akushon/action/node/action_manager.cpp
>    }
You can just remove the try-catch block in here.

2024-04-29 04:35 UTC, threeal approved these changes

2024-04-29 17:07 UTC, merged