Feature/use time based interpolation
ichiro-its/akushon pull request #43
Opened 2024-05-20 17:56 UTC by FaaizHaikal

## Jira Link: 

## Description

Action poses can be changed using time. This results in much more smooth motion compared to the old speed based pose motion.

## Type of Change

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [x] Manual tested.

## Checklist:

- [x] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2024-05-23 16:11 UTC, hiikariri approved these changes

2024-05-24 04:47 UTC, threeal commented on src/akushon/action/model/action.cpp
> +}
It's better to simply expose the `time_based` property to be public.

2024-05-24 04:47 UTC, threeal commented on src/akushon/action/model/pose.cpp
> +}
Ditto.

2024-05-24 04:48 UTC, threeal requested changes

2024-05-24 04:48 UTC, threeal commented on src/akushon/action/process/joint_process.cpp
> +  if (time_is_reached) {
Unnecessary `time_is_reached` variable:
```suggestion
  double passed_time = time - initial_time;
  double divider = passed_time / action_time;

  if (divider >= 1.0) {
```

2024-05-27 05:02 UTC, threeal approved these changes

2024-05-27 06:42 UTC, merged